### ISSUE TITLE
Delayed showing backgrounds

### ISSUE THREAD

**Issue by jeroenpardon** [marcelveldt/script.skin.helper.backgrounds#2]
Hi Marcel,

I am using Skin.SetString(SkinHelper.RandomFanartDelay,30) for a background slideshow on my homescreen. It seems like the value set here also determines how long it takes for the first image to show up. I am setting the string at startup and using Window(Home).Property(SkinHelper.AllVideosBackground) in a multiimage control, and after entering the homescreen it will take 30 seconds before I see any image.

**Comment by jeroenpardon** [comment]
Hi Marcel, any chance you could look into this?

In case you need a log: https://gist.github.com/jeroenpardon/8e86187ae746c460b54f9b978786a7c9

**Comment by marcelveldt** [comment]
Sorry for getting back to this so late, really busy lately.
This should have been fixed already, can you confirm ?
